#!/bin/bash

#set -x

pushd $(pwd)

# Vagrant copies provision scripts to /tmp/vagrant-shell and runs from there.
# So we need to chdir back to the script's folder to start from.
if [ -d "/vagrant" ]
then
  CONFDIR="/vagrant/standalone"
else
  CONFDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

# This directory is our puppet confdir.
PROD_FILES="${CONFDIR}/../files"
HIERA_DIR="${CONFDIR}/../hieradata"
cd $CONFDIR

# Create fake environment pointing to the real env in the parent dir.
mkdir -p environments/production
mount --bind .. environments/production

# Generate suitable fileserver.conf.
: ${COMMON_FILES_DIR:="/tmp"}
cat > ${CONFDIR}/fileserver.conf << EOT
[common_files]
  path ${COMMON_FILES_DIR}
  allow *

[production_files]
  path ${PROD_FILES}
  allow *
EOT

# Generate suitable hiera.yaml
: ${HIERA_YAML_SRC:="${PROD_FILES}/shared/hiera/hiera.yaml"}
cat ${HIERA_YAML_SRC} \
| sed "/:hierarchy:/a \ \ - 'standalone'" \
| sed "/:datadir:/ s='.*'='${HIERA_DIR}'=" \
> ${CONFDIR}/hiera.yaml

# Apply.
puppet apply --confdir $CONFDIR "${CONFDIR}/../manifests" "$@"

# Scrap fake environment.
umount environments/production
rmdir environments/production

# Fix permissions to permit puppet master/agent work.
chown puppet:puppet -R /var/lib/puppet/reports

popd
exit 0

