#!/bin/bash

# Change pwd to the script directory.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Identify distro family.
if [ -f /etc/debian_version ]
then
  distro="debian"
elif [ -f /etc/redhat-release ]
then
  distro="redhat"
else
  echo "Unknown distro family";
  exit 1;
fi

# Install Puppet based on distro family.
case "$distro" in
  debian)
    apt-get install lsb-release
    RELEASE=$(lsb_release -c -s)
    wget https://apt.puppetlabs.com/puppetlabs-release-$RELEASE.deb
    dpkg -i puppetlabs-release-$RELEASE.deb
    apt-get install puppet
  ;;
  redhat)
    yum install redhat-lsb
    RELEASE=el-$(lsb_release -r -s | head -c1)
    rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-$RELEASE.noarch.rpm
    yum install puppet
  ;;
esac

gem install r10k -y
r10k puppetfile install ../Puppetfile -v

