#!/bin/bash

pushd $(pwd)

# Identify distro family.
if [ -f /etc/debian_version ]
then
  distro="debian"
elif [ -f /etc/redhat-release ]
then
  distro="redhat"
else
  echo "Unknown distro family";
  exit 1;
fi

# Install dependencies based on distro family.
case "$distro" in
  debian)
    RELEASE=wheezy # TODO# Leverage lsb-release
    wget https://apt.puppetlabs.com/puppetlabs-release-$RELEASE.deb
    dpkg -i puppetlabs-release-$RELEASE.deb
    apt-get update
    apt-get install puppet
  ;;
  redhat)
    RELEASE=el-6 # Change to el-5, el-7, fedora-19, fedora-20...
    rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-$RELEASE.noarch.rpm
    yum install puppet
  ;;
esac

