#!/bin/bash

#set -x

pushd $(pwd)

# Vagrant copies provision scripts to /tmp/vagrant-shell and runs from there.
# So we need to chdir back to the script's folder to start from.
if [ -d "/vagrant" ]
then
  CONFDIR="/vagrant/standalone"
else
  CONFDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

# Identify distro family.
if [ -f /etc/debian_version ]
then
  distro="debian"
elif [ -f /etc/redhat-release ]
then
  distro="redhat"
else
  echo "Unknown distro family";
  exit 1;
fi

# Install Puppet based on distro family.
case "$distro" in
  debian)
    apt-get install lsb-release
    RELEASE=$(lsb_release -c -s)
    wget https://apt.puppetlabs.com/puppetlabs-release-$RELEASE.deb -P /tmp
    dpkg -i /tmp/puppetlabs-release-$RELEASE.deb
    apt-get install puppet hiera facter -y
    apt-get install git -y
  ;;
  redhat)
    yum install redhat-lsb
    RELEASE=el-$(lsb_release -r -s | head -c1)
    rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-$RELEASE.noarch.rpm
    yum install puppet
    yum install git
  ;;
esac

gem install r10k

cd "${CONFDIR}/.."
r10k puppetfile install Puppetfile -v

popd
exit 0

